name: lint
on: [pull_request, workflow_dispatch]
jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --production=false
      - run: npm run lint
